//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGML
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etape3
    {
        public string NOM { get; set; }
        public string TELEPHONE { get; set; }
        public string NIV { get; set; }
        public string MODELE { get; set; }
        public int ANNEE { get; set; }
    }
}
