//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGML
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        public Nullable<System.DateTime> DATEDEBUT { get; set; }
        public Nullable<System.DateTime> DATEPAIEMENT { get; set; }
        public Nullable<decimal> MONTANT { get; set; }
        public Nullable<int> NBRPAIEMENT { get; set; }
        public string NIV { get; set; }
        public int TERME { get; set; }
        public int IDCLIENT { get; set; }
        public Nullable<int> KM_DEBUT { get; set; }
        public Nullable<int> KM_FIN { get; set; }
        public Nullable<decimal> VALEUR { get; set; }
        public Nullable<bool> USAGE { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual TERME TERME1 { get; set; }
        public virtual VEHICULE VEHICULE { get; set; }
    }
}
