//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGML
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTION
    {
        public string NIV { get; set; }
        public Nullable<bool> TRANSMISSIONAUTO { get; set; }
        public Nullable<bool> CLIMATISATION { get; set; }
        public Nullable<bool> ANTIDEMARREUR { get; set; }
    
        public virtual VEHICULE VEHICULE { get; set; }
    }
}
