//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGML
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAIEMENT
    {
        public int IDTRANSACTION { get; set; }
        public Nullable<decimal> MONTANT { get; set; }
        public bool ANNULER { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string NIV { get; set; }
        public int IDCLIENT { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual VEHICULE VEHICULE { get; set; }
    }
}
