//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGML
{
    using System;
    using System.Collections.Generic;
    
    public partial class TERME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TERME()
        {
            this.LOCATIONS = new HashSet<LOCATION>();
        }
    
        public int ID { get; set; }
        public string TERME1 { get; set; }
        public Nullable<int> NBRANNEE { get; set; }
        public Nullable<int> NBRKM { get; set; }
        public Nullable<decimal> PRIMEKM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCATION> LOCATIONS { get; set; }
    }
}
