//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGML
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEHICULE()
        {
            this.LOCATIONS = new HashSet<LOCATION>();
            this.PAIEMENTS = new HashSet<PAIEMENT>();
        }
    
        public string NIV { get; set; }
        public int MODELE { get; set; }
        public int ANNEE { get; set; }
        public int TYPE { get; set; }
        public int COULEUR { get; set; }
    
        public virtual COULEUR COULEUR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCATION> LOCATIONS { get; set; }
        public virtual MODELE MODELE1 { get; set; }
        public virtual OPTION OPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAIEMENT> PAIEMENTS { get; set; }
        public virtual TYPE TYPE1 { get; set; }
    }
}
